module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
        "config",
        "env",
        "lint",
        "deps",
        "infra",
        "init",
        "security",
        "ui",
        "ux",
        "types",
        "log",
        "mock",
        "i18n",
        "meta",
        "data",
        "schema",
        "cleanup",
        "dev",
        "wip",
      ],
    ],
    "subject-case": [2, "always", "lower-case"],
    "subject-empty": [2, "never"],
    "header-max-length": [2, "always", 72],
    "type-case": [2, "always", "lower-case"],
    "scope-empty": [0, "always"],
  },
};
