export default {
  loginUser: 'auth/loginUser',
  getCategories: 'categories',
  deleteCategory: 'categories',
  addCategory: 'categories',
  getCategoryById: 'categories/getById',
  getAllCategories: 'categories/getAll',
  getFlat: 'categories/getFlat',
  getChildren: 'categories/children',
  editCategory: 'categories/edit',
  getAllAttributes: 'attributes/getAll',
  getAttributesById: 'attributes/getById',
  editAttribute: 'attributes',
  addAttribute: 'attributes',
  deleteAttribute: 'attributes',
}
