export default {
  loginUser: 'auth/loginUser',
  deleteCategory: 'categories',
  addCategory: 'categories',
  getCategoryById: 'categories/getById',
  getAllCategories: 'categories/getAll',
  getCategories: 'categories',
  getChildren: 'categories/children',
  editCategory: 'categories',
  getAllAttributes: 'attributes/getAll',
  getAttributesById: 'attributes/getById',
  editAttribute: 'attributes',
  addAttribute: 'attributes',
  deleteAttribute: 'attributes',
  getAllUnits: 'units/getAll',
  getUnitsById: 'units/getById',
  editUnit: 'units',
  addUnit: 'units',
  deleteUnit: 'units',
  addAttributeOption: 'attributeOptions',
  editAttributeOption: 'attributeOptions',
  deleteAttributeOption: 'attributeOptions',
  getAllByIdAttributeOption: 'attributeOptions/getAllById',
  getCategoryAttributeById: 'categoryAttributes/getById',
  deleteCategoryAttribute: 'categoryAttributes',
  editCategoryAttribute: 'categoryAttributes',
  addCategoryAttribute: 'categoryAttributes',
}
